Implement write methods in VaultFormat8ProviderDecorator
cryptomator/cloud-access-java pull request #3
Opened 2020-08-05 15:02 UTC by SailReal

2020-08-05 15:46 UTC, overheadhunter requested changes

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/DirectoryIdCache.java
> +		});
I don't think this qualifies for async execution. Spawning a background task is probably more expensive than iterating over a few thousand entries (worst case!).

Good old Iterator-over-EntrySet-loop should be fine and is easier to debug, too (no race conditions).

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/DirectoryIdCache.java
> +	public CompletionStage<Void> evictFolderIncludingChilds(CloudPath cleartextPath) {
Correct: `evictIncludingChildren`. Even more correct: `evictIncludingDescendants` (all generations^^).

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/VaultFormat8ProviderDecorator.java
> +				return CompletableFuture.completedFuture(result);
I don't think there is a `result` in case of an `exception`. Use `folder` instead?

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/VaultFormat8ProviderDecorator.java
> +				return CompletableFuture.completedFuture(result);
Is this covered by tests?

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/VaultFormat8ProviderDecorator.java
> +						.thenCompose(unused -> dirIdCache.evictFolderIncludingChilds(node));
Can be `thenRun(() -> dirIdCache.evictIncludingDescendants(node))`, see above.

2020-08-05 15:46 UTC, overheadhunter commented on src/main/java/org/cryptomator/cloudaccess/vaultformat8/VaultFormat8ProviderDecorator.java
> +	private CloudPath getDirPathFromClearTextDir(byte[] dirId) {
rename to `getDirPathWithId(...)`

2020-08-05 21:17 UTC, SailReal commented
Thanks for the good feedback. I considered everything as useful and changed it.
To test the handler in `createFolder(...)` if the parent of the dir-folder already exists I added a new test scenario.

2020-08-10 09:36 UTC, overheadhunter approved these changes

2020-08-10 09:36 UTC, merged